# FindCBLAS
# ---------
# sparselizard needs exactly one BLAS entry point, cblas_dgemm in densemat.cpp,
# reached through a C interface header.
#
# The header name is not portable: the reference implementation and OpenBLAS
# install cblas.h, oneMKL installs mkl_cblas.h, and some distributions bury it
# in an openblas/ subdirectory. Rather than patching the source for each vendor,
# a one-line relay header named cblas.h is generated in the build tree whenever
# the vendor header goes by another name.
#
# The library itself is looked up with the stock FindBLAS module, so the usual
# BLA_VENDOR switch applies, e.g. -DBLA_VENDOR=Intel10_64lp_seq for oneMKL.
#
# Result:
#   CBLAS_FOUND
#   CBLAS::CBLAS

include(FindPackageHandleStandardArgs)

find_package(BLAS QUIET)

set(CBLAS_HEADER_HINTS "")
if(DEFINED ENV{MKLROOT})
    list(APPEND CBLAS_HEADER_HINTS "$ENV{MKLROOT}/include")
endif()

find_path(CBLAS_INCLUDE_DIR
    NAMES cblas.h mkl_cblas.h
    HINTS ${CBLAS_HEADER_HINTS}
    PATH_SUFFIXES openblas blis)

if(CBLAS_INCLUDE_DIR)
    if(EXISTS "${CBLAS_INCLUDE_DIR}/cblas.h")
        set(CBLAS_HEADER_NAME "cblas.h")
    else()
        set(CBLAS_HEADER_NAME "mkl_cblas.h")
    endif()
endif()

find_package_handle_standard_args(CBLAS
    REQUIRED_VARS CBLAS_INCLUDE_DIR BLAS_FOUND)

if(CBLAS_FOUND AND NOT TARGET CBLAS::CBLAS)
    set(_cblas_incs "${CBLAS_INCLUDE_DIR}")

    if(NOT CBLAS_HEADER_NAME STREQUAL "cblas.h")
        # densemat.cpp includes "cblas.h" unconditionally; give it one.
        set(_shim_dir "${CMAKE_BINARY_DIR}/cblas-shim")
        file(MAKE_DIRECTORY "${_shim_dir}")
        file(WRITE "${_shim_dir}/cblas.h"
"/* Generated by cMake/FindCBLAS.cmake -- do not edit.
   This BLAS installation exposes its C interface as <${CBLAS_HEADER_NAME}>. */
#pragma once
#include <${CBLAS_HEADER_NAME}>
")
        # After the vendor directory, so a real cblas.h always wins.
        list(APPEND _cblas_incs "${_shim_dir}")
        message(STATUS "CBLAS: relay header generated for ${CBLAS_HEADER_NAME}")
    endif()

    add_library(CBLAS::CBLAS INTERFACE IMPORTED)
    set_target_properties(CBLAS::CBLAS PROPERTIES
        INTERFACE_INCLUDE_DIRECTORIES "${_cblas_incs}"
        INTERFACE_LINK_LIBRARIES "${BLAS_LIBRARIES}")
endif()

mark_as_advanced(CBLAS_INCLUDE_DIR)
